# Application Name
spring.application.name=url-shortener

# Server Configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always



# URL Shortener Configuration
app.url-shortener.base-url=http://localhost:8080
app.url-shortener.default-expiry-days=30
app.url-shortener.max-custom-alias-length=50

# Logging
logging.level.com.urlshortener=DEBUG
logging.level.org.springframework.web=INFO
