INSERT INTO urls (
    id,
    short_code,
    original_url,
    custom_alias,
    title,
    description,
    click_count,
    created_at,
    expires_at,
    last_accessed_at,
    active,
    password
)
VALUES
    (
        -1,
        'google',
        'https://www.google.com',
        'google',
        'Google',
        'Search engine',
        15,
        NOW() - INTERVAL '5 days',
        NOW() + INTERVAL '25 days',
        NOW() - INTERVAL '2 hours',
        true,
        NULL
    ),
    (
        -2,
        'github',
        'https://www.github.com',
        'github',
        'GitHub',
        'Code repository',
        42,
        NOW() - INTERVAL '10 days',
        NOW() + INTERVAL '20 days',
        NOW() - INTERVAL '5 hours',
        true,
        NULL
    ),
    (
        -3,
        'stackoverflow',
        'https://www.stackoverflow.com',
        'stackoverflow',
        'Stack Overflow',
        'Developer Q&A',
        28,
        NOW() - INTERVAL '3 days',
        NOW() + INTERVAL '27 days',
        NOW() - INTERVAL '1 hour',
        true,
        NULL
    ),
    (
        -4,
        'youtube',
        'https://www.youtube.com',
        'youtube',
        'YouTube',
        'Video platform',
        100,
        NOW() - INTERVAL '15 days',
        NOW() + INTERVAL '15 days',
        NOW() - INTERVAL '10 hours',
        true,
        NULL
    ),
    (
        -5,
        'linkedin',
        'https://www.linkedin.com',
        'linkedin',
        'LinkedIn',
        'Professional network',
        8,
        NOW() - INTERVAL '1 day',
        NOW() + INTERVAL '29 days',
        NOW() - INTERVAL '20 hours',
        true,
        NULL
    ),
    (
        -6,
        'medium',
        'https://www.medium.com',
        'medium',
        'Medium',
        'Blogging platform',
        35,
        NOW() - INTERVAL '7 days',
        NOW() + INTERVAL '23 days',
        NOW() - INTERVAL '3 hours',
        true,
        NULL
    ),
    (
        -7,
        'twitter',
        'https://www.twitter.com',
        'twitter',
        'Twitter/X',
        'Social media',
        67,
        NOW() - INTERVAL '12 days',
        NOW() + INTERVAL '18 days',
        NOW() - INTERVAL '8 hours',
        true,
        NULL
    ),
    (
        -8,
        'reddit',
        'https://www.reddit.com',
        'reddit',
        'Reddit',
        'Community forum',
        23,
        NOW() - INTERVAL '4 days',
        NOW() + INTERVAL '26 days',
        NOW() - INTERVAL '12 hours',
        true,
        NULL
    ),
    (
        -9,
        'wikipedia',
        'https://www.wikipedia.org',
        'wikipedia',
        'Wikipedia',
        'Encyclopedia',
        56,
        NOW() - INTERVAL '20 days',
        NOW() + INTERVAL '10 days',
        NOW() - INTERVAL '15 hours',
        true,
        NULL
    ),
    (
        -10,
        'amazon',
        'https://www.amazon.com',
        'amazon',
        'Amazon',
        'E-commerce',
        89,
        NOW() - INTERVAL '8 days',
        NOW() + INTERVAL '22 days',
        NOW() - INTERVAL '6 hours',
        true,
        NULL
    )
    ON CONFLICT (short_code) DO NOTHING;